skip_commits:
  message: /^Merge pull request /

build: false

environment:
  PYTHONIOENCODING: "UTF-8"

  matrix:
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35"

    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"

    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      CONDA_PY: "36"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36"

    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"

install:
    # Use the pre-installed Miniconda for the desired arch
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda update -y -q conda
    - cmd: conda install -y -q -c conda-forge -c cmutel numpy scipy psutil bw2parameters appdirs arrow docopt docutils jinja2 lxml pandas pyprind pytest stats_arrays cytoolz wrapt voluptuous

test_script:
  - "pytest"
  - "python setup.py -q install"
  - "python.exe tests/manual/run_all_ci.py"
