# Modified from https://ci.appveyor.com/project/jkbrzt/httpie
build: false

environment:
  matrix:
    - PYTHON: "C:/Python35"

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements-appveyor.txt"

test_script:
  - "%PYTHON%/Scripts/py.test.exe"
  # - "%PYTHON%/Scripts/http.exe --debug"
  # - "%PYTHON%/python.exe setup.py test"
