# Modified from https://ci.appveyor.com/project/jkbrzt/httpie
build: false

environment:
  matrix:
    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_NPY: "110"

    - PYTHON: "C:\\Python35_32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"
      CONDA_NPY: "110"

install:
  - powershell .\\ci\\appveyor-install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install --no-cache-dir -r requirements.txt"

test_script:
  - "py.test"
  - "python setup.py -q install"
  - "python.exe tests/manual/run_all_ci.py"
