# Modified from https://ci.appveyor.com/project/jkbrzt/httpie
build: false

environment:
  matrix:
    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_NPY: "110"

    - PYTHON: "C:\\Python35_32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"
      CONDA_NPY: "110"

install:
  - powershell .\\ci\\appveyor-install.ps1
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

test_script:
  - "%PYTHON%/Scripts/py.test.exe"
  - "%PYTHON%/python.exe setup.py -q install"
  - "%PYTHON%/python.exe tests/manual/run_all_ci.py"
